// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udzxkqpfibineuowimvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkenhrcXBmaWJpbmV1b3dpbXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Njg4NTUsImV4cCI6MjA2MTI0NDg1NX0.Idn3odtOnDXkxyc7XkBhMZFQ1MAdKwhpqeoG416TR3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);